Added slides for Get Another Label
sfu-db/cmpt884-fall16 pull request #7
Opened 2016-09-28 23:24 UTC by ajakash91

Added slides for Get Another Label and created a link for the same in index.html

2016-09-28 23:58 UTC, jnwang requested changes
Seems like you missed the right part of the single quotes for the URL:

 'https://github.com/sfu_db/cmpt884-fall16/blob/master/Lectures/Get_Another_Label_slides.pdf

2016-09-29 01:21 UTC, ajakash91 commented
Okay, I will correct it.

Regards,
Akash A J

On 28 Sep 2016 16:58, "Jiannan Wang" <notifications@github.com> wrote:

> *@jnwang* requested changes on this pull request.
>
> Seems like you missed the right part of the single quotes for the URL:
>
> 'https://github.com/sfu_db/cmpt884-fall16/blob/master/
> Lectures/Get_Another_Label_slides.pdf
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sfu-db/cmpt884-fall16/pull/7#pullrequestreview-2052349>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQLu7LPw7eSZFFXf3qQeoc7pXbuZDnHNks5quv85gaJpZM4KJbDM>
> .
>

2016-09-29 18:49 UTC, ajakash reviewed
Have added the single quote.

2016-09-30 15:23 UTC, jnwang approved these changes

2016-09-30 15:23 UTC, merged